"""add_event_ticker_market_stats

Revision ID: 1a90b613abd3
Revises: 653f78d3c818
Create Date: 2026-06-02 21:28:54.747054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a90b613abd3'
down_revision: Union[str, None] = '653f78d3c818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_stats',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('series_ticker', sa.String(), nullable=True),
    sa.Column('num_candles', sa.Integer(), nullable=True),
    sa.Column('data_start_date', sa.Date(), nullable=True),
    sa.Column('data_end_date', sa.Date(), nullable=True),
    sa.Column('avg_volume', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('price_volatility', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('avg_spread_cents', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pct_candles_with_data', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('rank_score', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['markets.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.alter_column('market_prices', 'volume',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.add_column('markets', sa.Column('event_ticker', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'event_ticker')
    op.alter_column('market_prices', 'volume',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_table('market_stats')
    # ### end Alembic commands ###
